language: go

go:
  - 1.9

os:
  - linux
  # - osx

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

install:
  - go get -t ./...
  - go get golang.org/x/lint/golint
  - go get github.com/gordonklaus/ineffassign
  - phantomjs --version

script:
  # todo exclude vendors from diff or format them and commit
  #- diff <(echo -n) <(gofmt -s -d .)
  - go list -f '{{.Dir}}' ./... | grep -v /vendor/ | xargs -n 1 ineffassign
  - go vet $(go list ./... | grep -v /vendor/)
  - go test $(go list ./... | grep -v /vendor/)
  - go test -race -count=2 $(go list ./... | grep -v /vendor/)

after_script:
  - golint $(go list ./... | grep -v /vendor/)
  - go test -run=🤐 -bench=. -count=1 -benchmem $(go list ./... | grep -v /vendor/)
  - cat cmd/ht/example-tests/1_Test.NoneHTTP.Bash/result.txt
